namespace Ingenico
{


	public enum E_DataListTag
	{
		ECR_TRANSACTION_AMOUNT = 1,
		ECR_TENDER_TYPE = 2,
		ECR_CLERK_ID = 3,
		ECR_INVOICE_NUM = 4,
		ECR_AUTHORIZATION_NUM = 5,
		ECR_ORIG_REF_NUM = 6,
		ECR_CLOSE_BATCH = 7,
		ECR_FORCED_UP = 8,
		ECR_DCC = 9,
		ECR_CUST_REF_NUM = 10,
		ECR_REF_NUM = 11,
		ECR_PAN_NUM = 12,
		ECR_TRAN_TYPE = 13,
		ECR_SPECIFIC_DATA = 14,
		ECR_FORMATTED_RCPT_VAL = 15,
		ECR_FINAL_AMOUNT = 16,
		ECR_TRACE_NUM = 20,
		ECR_VAS_MER_URL = 30,
		ECR_VAS_MER_ID = 31,
		ECR_VAS_FILTER_CATG = 32,
		ECR_VAS_ENCRYPT_REQ = 33,
		ECR_VAS_MODE = 34,
		ECR_VAS_MERCH_INDEX = 35,
		ECR_VAS_PRIVATE_KEY = 36,
		ECR_REPRINT_TYPE = 50,
		ECR_PARAM_TYPE = 51,
		ECR_RCPT_NAME = 52,
		ECR_ORIG_SEQ_NUM = 112
	}
}